version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: recipe-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - recipe-network

  # Deno Backend API
  backend:
    build:
      context: ./deno-recipe-app
      dockerfile: ../Dockerfile-backend
    container_name: recipe-backend
    # restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://recipe_user:recipe_password@database:5432/recipe_db
      - PORT=8010
      - DENO_DIR=/deno-dir
    ports:
      - "8010:8010"
      - "4983:4983"
    depends_on:
      - database
    networks:
      - recipe-network
    volumes:
      - ./deno-recipe-app/app:/app
      - deno-cache:/deno-dir

  # Angular Frontend
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile-frontend
    container_name: recipe-frontend
    # restart: unless-stopped
    ports:
      - "80:80"
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - recipe-network
    # volumes:
    #   - ./angular-recipe-app:/app


volumes:
  postgres_data:
    driver: local
  deno-cache:
    driver: local

networks:
  recipe-network:
    driver: bridge
